### ISSUE TITLE
Roadmap question: dropping Python 2.X

### ISSUE THREAD

**Issue by arrdem** [indico/flask-multipass#36]
As Python 2.X is solidly end of lifed at this point, at what point do y'all intend for Multipass to go py3k only? Or is maintaining py2k capability something y'all desire?

No opinion either way, Multipass works great on py3k, I just don't want to put up py3k only PRs if that isn't consistent with the roadmap.

Thanks!

**Comment by ThiefMaster** [comment]
Hi, I think removing py2 support just needs pyupgrade applied to the codebase and maybe removing a few unused six imports manually... so not sure if a PR for it is that useful (it's the kind of thing that's probably easier to do ourselves once we are ready to switch, since that way it's less likely it conflicts with any changes someone makes in parallel).

Anyway, about the roadmap question: Once we released Indico 3.0 (in Q1 2021) which will also be Python3-only, we plan to drop Python 2 in all our other libraries as well (even though we might support more 3.x versions here (e.g. 3.6+ or 3.7+), even though Indico will require Python 3.9+).

**Comment by arrdem** [comment]
Great! Thanks for the info!
